### ISSUE TITLE
Add a command modifier to the sed correction feature so that one can modify *their* last message, instead of *the* last message

### ISSUE THREAD

**Issue by simsid66** [mikellama/ircbot-llama#19]

**Comment by mikellama** [comment]
how to specify when to do the vs their? just always default to that person's if it exists in the 20 message buffer?

**Comment by simsid66** [comment]
no, you could do something like ?/<special character>/<old>/<new>

**Comment by PhilLaFayette** [comment]
When can we expect this implementation? Probably by this weekend, right?

**Comment by mikellama** [comment]
Right

**Comment by mikellama** [comment]
You can now use ?s/ to change _your_ messages only.
