### ISSUE TITLE
License headers and copyright holder

### ISSUE THREAD

**Issue by 2mac** [mikellama/ircbot-llama#2]
Please put license header comments in each code file, and include copyright date and copyright holder in the headers and in the main license file.

**Comment by mikellama** [comment]
okay.

**Comment by mikellama** [comment]
That should do it. Thanks.

**Comment by 2mac** [comment]
Not to nitpick, but there are a couple of issues. The minor one is that the LICENSE file should not be formatted like a program; it should be formatted like a document. Basically remove the comment syntax and the `#!` line.

Next, the copyright holder needs to be a real entity. Sure, we know you as mikellama, but if for whatever reason there were a legal dispute, the courts don't know who mikellama is. It either needs to be your name or a legal entity which you can represent.

**Comment by mikellama** [comment]
Got it. Thanks again.
