### ISSUE TITLE
[Feature Request] Should parse direct comment links

### ISSUE THREAD

**Issue by PhilLaFayette** [mikellama/ircbot-llama#22]
Where `<Aztec03> https://github.com/mikellama/ircbot-llama/issues/19`
gives: `<buttbot> ^ Add a command modifier to the sed correction feature so that one can modify *their* last message, instead of *the* last message · Issue #19 · mikellama/ircbot-llama · GitHub`

However, `<Aztec03> https://github.com/mikellama/ircbot-llama/issues/19#issuecomment-379956212`
gives: `<buttbot> ^ Add a command modifier to the sed correction feature so that one can modify *their* last message, instead of *the* last message 路 Issue #19 路 mikellama/ircbot-llama 路 GitHub`

instead of `When can we expect this implementation? Probably by this weekend, right?`

**Comment by mikellama** [comment]
Not sure what you are asking for here.
