### ISSUE TITLE
[FEATURE REQUEST] Send an invite to a certain person if they are in a preapproved list of nicks upon the receipt of a certain command in PM.

### ISSUE THREAD

**Issue by simsid66** [mikellama/ircbot-llama#31]
What with the new invite-only policy, this would be a good way for someone to get in if no one from llamas is around to invite them and they're a trusted person.

**Comment by mike-rose** [comment]
if they are a trusted person, they should just request to be added to the actual list so no invite is required. 2 trusted llama lists is unnecessary.
