### ISSUE TITLE
[FEATURE REQUEST] Reminder system

### ISSUE THREAD

**Issue by simsid66** [mikellama/ircbot-llama#34]
A reminder system for pronk, to remind a user of something.

Like so:
?reminder in <time period> remindme <task>
?reminder in 6m remindme noodles

**Comment by TheDetectiveTaco** [comment]
@mike-llama may add this in the near future, but also in the near future the whole bot is going to be basically reconstructed into a modular type of bot like supybot, and other bots. So all the capabilities it has right now will be modules so people can pick and choose what they want. But I’m sure that will be added.

**Comment by simsid66** [comment]
Alright, thank you.
