### ISSUE TITLE
&amp; issue

### ISSUE THREAD

**Issue by llam-en** [mikellama/ircbot-llama#9]
Bug spotted:

22:05 < rjphares> ?song
22:05 <+pronk> Soul Low - JD &amp; Me

**Comment by mikellama** [comment]
what is the bug here?

**Comment by llam-en** [comment]
The issue was that `&` was appearing in the channel as `&amp;`.
It appeared as the & amp ; when I typed it sorry. I think that github may have translated it into &.

**Comment by mikellama** [comment]
okay. I thought that might have been it. duckgoose has suggested using the html module. Waiting on d to install it. He is admin on pronk's new VM host.

**Comment by mikellama** [comment]
dood. Mr. DuckGoose just fixed this. Go team llamas.
